pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - status-success=Travis CI - Pull Request
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: squash
  - name: delete head branch on merged pull requests
    conditions:
      - merged
    actions:
      delete_head_branch:
  - name: add enhancement label
    actions:
      label:
        add: [ enhancement ]
