# PLEASE DO NOT EDIT THIS FILE. EDIT Templates/adoptopenjdk.rb.tmpl
cask "adoptopenjdk11-openj9-large" do
  version "11.0.10,9"
  sha256 "8ec1259154270c86ab3b14793534b666e0021cee8ae9dc76202832b4df940933"

  # github.com/AdoptOpenJDK was verified as official when first introduced to the cask
  url "https://github.com/AdoptOpenJDK/openjdk#{version.major}-binaries/releases/download/jdk-11.0.10%2B9_openj9-0.24.0/OpenJDK11U-jdk_x64_mac_openj9_macosXL_11.0.10_9_openj9-0.24.0.pkg",
      verified: "https://github.com/AdoptOpenJDK"
  livecheck "https://github.com/AdoptOpenJDK/openjdk#{version.major}-binaries/releases/latest"
  name "AdoptOpenJDK 11 (OpenJ9) (XL)"
  desc "AdoptOpenJDK OpenJDK (Java) Development Kit"
  homepage "https://adoptopenjdk.net/"

  pkg "OpenJDK11U-jdk_x64_mac_openj9_macosXL_11.0.10_9_openj9-0.24.0.pkg"

  postflight do
    system_command "/usr/sbin/pkgutil", args: ["--pkg-info", "net.adoptopenjdk.11-openj9.jdk"], print_stdout: true
  end

  uninstall pkgutil: "net.adoptopenjdk.11-openj9.jdk"

  caveats do
    discontinued

    <<~EOS
      Large Heap Casks have now been deprecated. Please use the Normal Heap Casks instead.
      See https://github.com/AdoptOpenJDK/openjdk-build/issues/2426 for more information.
    EOS
  end
end
