# PLEASE DO NOT EDIT THIS FILE. EDIT Templates/adoptopenjdk.rb.tmpl
cask 'adoptopenjdk14' do
  version '14,36'
  sha256 'c55f1ae6c0c9e48ef4e9a4dc9c6d29a668bb06ae43d168c05c17028c56139b23'

  # github.com/AdoptOpenJDK was verified as official when first introduced to the cask
  url 'https://github.com/AdoptOpenJDK/openjdk14-binaries/releases/download/jdk-14%2B36/OpenJDK14U-jdk_x64_mac_hotspot_14_36.pkg'
  appcast "https://github.com/AdoptOpenJDK/openjdk#{version.major}-binaries/releases/latest"
  name 'AdoptOpenJDK 14'
  homepage 'https://adoptopenjdk.net/'

  pkg 'OpenJDK14U-jdk_x64_mac_hotspot_14_36.pkg'

  postflight do
    system_command '/usr/sbin/pkgutil', args: ['--pkg-info', 'net.adoptopenjdk.14.jdk'], print_stdout: true
  end

  uninstall pkgutil: 'net.adoptopenjdk.14.jdk'
end
