# PLEASE DO NOT EDIT THIS FILE. EDIT Templates/adoptopenjdk.rb.tmpl
cask "adoptopenjdk-jre" do
  version "16.0.1,9"
  sha256 "e1dca31bb02c2de72b0a3789a3a67336fd04ab6c720f127cae42fda0c789986f"

  # github.com/AdoptOpenJDK was verified as official when first introduced to the cask
  url "https://github.com/AdoptOpenJDK/openjdk#{version.major}-binaries/releases/download/jdk-16.0.1%2B9/OpenJDK16U-jre_x64_mac_hotspot_16.0.1_9.pkg",
      verified: "https://github.com/AdoptOpenJDK"
  livecheck "https://github.com/AdoptOpenJDK/openjdk#{version.major}-binaries/releases/latest"
  name "AdoptOpenJDK 16 (JRE)"
  desc "AdoptOpenJDK OpenJDK (Java) Development Kit"
  homepage "https://adoptopenjdk.net/"

  pkg "OpenJDK16U-jre_x64_mac_hotspot_16.0.1_9.pkg"

  postflight do
    system_command "/usr/sbin/pkgutil", args: ["--pkg-info", "net.adoptopenjdk.16.jre"], print_stdout: true
  end

  uninstall pkgutil: "net.adoptopenjdk.16.jre"
end
