name: Updater

on: 
    workflow_dispatch:
        inputs:
            force:
                description: 'Force update the cask or not. Set to True if needed'     
                required: true
                default: 'False'
    schedule:
        - cron: '0 0 * * *' # every day

jobs:
  updater:
    if: startsWith(github.repository, 'AdoptOpenJDK/')
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        repository: adoptopenjdk-github-bot/homebrew-openjdk
        token: ${{ secrets.ACCESS_TOKEN }}
        ssh-key: ${{ secrets.ADOPT_BOT_SSH_PRIVATE }}
        
    - name: Setup Git repos
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git remote rename origin fork
        git remote add upstream https://github.com/AdoptOpenJDK/homebrew-openjdk.git
        git remote -v
        git fetch --all
        git reset --hard upstream/master

    - name: Run updater
      run: |
        FORCE=${{ github.event.inputs.force }}
        if [ "$FORCE" == "True" ]; then
            force_flag="--force"
        fi
        bash auto_updater.sh --push "$force_flag"
      env:
        GITHUB_USER: adoptopenjdk-github-bot
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
